displayName=Verzik Yellows
author=javlanoob
description=Renders yellows at Verzik P3 above everything else
tags=verzik,yellow,yellows,tob,theatre,blood,raid
plugins=com.verzikyellows.VerzikYellowsPlugin
build=standard
